---
deployment:
  tasks:
    - export DEPLOYPATH=/home/nathanh3/public_html/
    - /bin//cp index.html $DEPLOYPATH
    - /bin/cp -R images $DEPLOYPATH
    - /bin/cp -R html $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH
    - /bin/cp -R mail $DEPLOYPATH
    - /bin/cp -R scss $DEPLOYPATH
    - /bin/cp -R slick $DEPLOYPATH
    - /bin/cp -R styles $DEPLOYPATH
    - /bin/cp -R vendor $DEPLOYPATH
    - /bin/cp -R "Word Guess" $DEPLOYPATH
    - /bin//cp .browserslistrc $DEPLOYPATH
    - /bin//cp .travis.yml $DEPLOYPATH
    - /bin//cp gulpfile.js $DEPLOYPATH
    - /bin//cp LICENSE $DEPLOYPATH
    - /bin//cp package-lock.json $DEPLOYPATH
    - /bin//cp package.json $DEPLOYPATH
    - /bin//cp README.md $DEPLOYPATH